data:
    dataset: CUB200
    imgs_dir: /home/voz/shared/database/cbm/cub2002011/versions/7/CUB_200_2011/images
    pkls_dir: /home/voz/shared/database/cbm/cub2002011/versions/7/CUB_200_2011/pickles
    attr_dir: /home/voz/shared/database/cbm/cub2002011/versions/7/CUB_200_2011/attributes
    modify_pkls: True
    n_groups_concepts: 12

model:
    model_type: shcbm
    encoder:
        arch: inception_v3
        hidden_dim: 1024
        pretrained: true
    hidden_dims_y: 256
    var_z: 0
    hidden_dims_c: null
    beta: 0.1
    gamma: 0.01

training:
    batch_size: 128
    n_epochs: 250
    save_epochs: 100
    optimizer:    
        optimizer: SGD
        base_batch_size: 64
        base_lr: 0.01
        batch_size: 128
        momentum: 0.9
        weight_decay: 0.00004
    scheduler:
        gamma: 0.1
        scheduler: StepLR
        step_size: 100
