data:
    dataset: MPI3D
    filepath: /mnt/cephfs/home/voz/shared/database/disentanglement/mpi3d/mpi3d_real.npz
    task: object_shape
    concepts: [object_color, object_size, camera_height, background_color]
    nuisances_task: [horizontal_axis]

model:
    model_type: cbm
    encoder:
        arch: resnet20
    hidden_dims_y: 64
    var_z: 0
    hidden_dims_c: null
    beta: 1

training:
    batch_size: 128
    n_epochs: 50
    save_epochs: 10
    optimizer:    
        optimizer: SGD
        base_batch_size: 64
        base_lr: 0.003
        batch_size: 128
        momentum: 0.9
        weight_decay: 0.00004
    scheduler:
        gamma: 0.1
        scheduler: StepLR
        step_size: 20
